version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    environment:
    #put your local machine ip
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_CREATE_TOPICS: twitters:1:1, outputtopic1:1:1, outputtopic2:1:1, outputtopic3:1:1, vantage:1:1, device:1:1, got_reponded:1:1, encode_tweets:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
